version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

jobs:
  build-windows:
    executor:
      name: unity/ubuntu
      editor_version: 2021.3.8f1
      resource_class: large
      target_platform: windows-mono
    steps:
      - checkout
      - unity/prepare-env:
          project-path: "src"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
      - unity/build:
          build-name: "MyBuild"
          build-target: StandaloneWindows64
          project-path: "src"
      - unity/return-license

workflows:
  build-unity-project:
    jobs:
      - build-windows:
          context: orb-testing-unity
      - unity/build:
          build-target: StandaloneWindows64
          context: orb-testing-unity
          project-path: "src"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          executor:
            name: unity/ubuntu
            editor_version: 2021.3.8f1
            resource_class: large
            target_platform: windows-mono